version: v1.1
embedder:
  provider: openai
  config:
    apiKey: test-api-key
    model: text-embedding-3-small
vectorStore:
  provider: memory
  config:
    collectionName: test-memories
    dimension: 1536
llm:
  provider: openai
  config:
    apiKey: test-api-key
    model: gpt-4-turbo-preview
historyDbPath: test-memory.db
